name: "Add application"
description: "A template for requesting an application's addition to the list at the ArConnect webiste"
title: '[APP] Add "appname" to apps list'
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        **Thank you for submitting a new application to the list of apps that support ArConnect. Please make sure that the app is not already in the list at [arconnect.io/apps](https://www.arconnect.io/apps)!**

  - type: input
    id: appname
    attributes:
      label: Application name
      description: What is the name of the application you wish to add?
      placeholder: App name...
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Application description
      description: Please provide a simple description of 150-250 characters for the app.
      placeholder: App description...
    validations:
      required: true

  - type: markdown
    id: assets
    attributes:
      label: Application logo & thumbnail
      description: Please upload your application's logo and thumbnail images.
      value: App logo \nApp name
    validations:
      required: true

  - type: input
    id: website
    attributes:
      label: Application website
      description: Please provide the URL of the application's website.
      placeholder: e.g. https://ardrive.io
    validations:
      required: true
